import type { NextPage } from 'next';
import Head from 'next/head';

import NoteOperation from '../components/note/NoteOperation';

const Home: NextPage = () => {
    return (
        <>
            <Head>
                <title>Note</title>
                <meta
                    name="description"
                    content="Generated by create next app" />
                <link
                    rel="icon"
                    href="/favicon.ico" />
            </Head>
            <div className="my-10 container">
                <div className="row">
                    <div className="col-md-3">
                        <NoteOperation />
                    </div>
                    <div className="col-md-9">
                        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolores dolorum fuga illo magni maxime minima provident totam ullam veritatis
                        voluptates? Ad
                        aspernatur delectus deleniti dignissimos eligendi ipsa iure minus nostrum!
                    </div>
                </div>
            </div>
        </>
    );
};

export default Home;
