import React from 'react';

import { useGlobalStateContext } from '../../../store/context/GlobalContext';

import HeaderMeta from '../headerMeta/HeaderMeta';
import Navigation from '../navigation/Navigation';

export type MainLayoutProps = {
    children: React.ReactNode;
};

const MainLayout = ({ children }: MainLayoutProps): React.ReactElement => {
    const { layout } = useGlobalStateContext();

    return (
        <>
            <HeaderMeta
                title="Note"
                meta={<meta
                    name="description"
                    content="Generated by create next app" />}
                favicon />
            {layout && <Navigation />}
            {children}
        </>
    );
};

export default MainLayout;